name: 'UE5-Build-Project'
description: 'Cook, stage, and package projects for Unreal Engine'
author: 'Orchid Isle Games'
branding:
  icon: 'anchor'
  color: 'green'

inputs:
  RUNUAT_PATH:
    description: 'Path to RunUAT.bat'
    required: true
  UPROJECT_PATH:
    description: 'Path to the .uproject file'
    required: true
  BUILD_CONFIG:
    description: 'Configuration to use'
    required: true
  PLATFORM:
    description: 'Platform to build for'
    required: true
  COOK:
    description: 'Whether to cook'
    required: false
    default: 'true'
  STAGE:
    description: 'Whether to stage'
    required: false
    default: 'true'
  PACKAGE:
    description: 'Whether to package'
    required: false
    default: 'false'
  PAK:
    description: 'Whether to pak files'
    required: false
    default: 'false'
  SERVER:
    description: 'Whether to include the server'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - shell: powershell
      run: |
        $runUatPath = "${{ inputs.RUNUAT_PATH }}"
        $uprojectPath = "${{ inputs.UPROJECT_PATH }}"
        $buildConfig = "${{ inputs.BUILD_CONFIG }}"
        $platform = "${{ inputs.PLATFORM }}"
        $serverArg = if (${{ inputs.SERVER }} -eq 'true') { "-server -serverplatform=$platform -noclient" } else { "" }
        $cookArg = if (${{ inputs.COOK }} -eq 'true') { "-cook" } else { "" }
        $stageArg = if (${{ inputs.STAGE }} -eq 'true') { "-stage" } else { "" }
        $pakArg = if (${{ inputs.PAK }} -eq 'true') { "-pak" } else { "" }
        $packageArg = if (${{ inputs.PACKAGE }} -eq 'true') { "-package" } else { "" }
        $command = "& `"$runUatPath`" BuildCookRun " +
                  "-project=`"$uprojectPath`" " +
                  "-clientconfig=$buildConfig -serverconfig=$buildConfig -platform=$platform " +
                  "$serverArg $cookArg $stageArg $pakArg $packageArg " +
                  "-noP4 -build"
        Invoke-Expression $command
