name: 'UE5-Build-Project'
description: 'Cook, stage, and package projects for Unreal Engine'
author: 'Orchid Isle Games'
branding:
  icon: 'anchor'
  color: 'green'

inputs:
  RUNUAT_PATH:
    description: 'Path to RunUAT.bat'
    required: true
  UPROJECT_PATH:
    description: 'Path to the .uproject file'
    required: true
  BUILD_CONFIG:
    description: 'Configuration to use'
    required: true
  PLATFORM:
    description: 'Platform to build for'
    required: true
  COOK:
    description: 'Whether to cook'
    required: false
    default: 'true'
  STAGE:
    description: 'Whether to stage'
    required: false
    default: 'true'
  PACKAGE:
    description: 'Whether to package'
    required: false
    default: 'false'
  PAK:
    description: 'Whether to pak files'
    required: false
    default: 'false'
  SERVER:
    description: 'Whether to include the server'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - shell: powershell
      run: |
        & "${{ inputs.RUNUAT_PATH }}" BuildCookRun `
        -project="${{ inputs.UPROJECT_PATH }}" `
        -clientconfig=${{ inputs.BUILD_CONFIG }} -serverconfig=${{ inputs.BUILD_CONFIG }} -platform=${{ inputs.PLATFORM }} `
        ${{ inputs.SERVER == 'true' && '-server -serverplatform=${{ inputs.PLATFORM }} -noclient' }} 
        -noP4 -build `
        ${{ inputs.COOK == 'true' && '-cook' }}
        ${{ inputs.STAGE == 'true' && '-stage' }}
        ${{ inputs.PAK == 'true' && '-pak' }}
        ${{ inputs.PACKAGE == 'true' && '-package' }}
